# -*- coding: utf-8 -*-
from __future__ import unicode_literals, division, print_function, absolute_import

import testdata

from herd.serverless.interface.aws import (
    Role,
    Lambda,
)


class TestCase(testdata.TestCase):
    @classmethod
    def get_role(self):
        desc = " ".join([
            "Autogenerated role for herd unit tests, this can be safely deleted",
            "but herd will re-create it if the unit tests are ran again",
        ])

        pout.v(desc)

        r = Role("herd-unittests", desc)
        #r.save()
        return r


class LambdaTest(TestCase):
    def test_bundle_dependencies(self):
        m = testdata.create_module(contents="")

        filepath = testdata.create_file("lambda-bundle-dependencies.py", contents=[
            "import boto3",
            "import {}".format(m),
            "import email",
            "",
            "def handler(event, context):",
            "    pass",
        ])

        l = Lambda(filepath, role=self.get_role())

        l.bundle()



    # TODO -- test local module with the same name as sys module

